main

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,4 +1,4 @@
-name: Build docker image and upload to ECR
+name: Build Docker Image, Upload to ECR and Deploy to ECS
 
 on:
   workflow_call:
@@ -13,7 +13,7 @@ jobs:
     environment: ${{ inputs.ENVIRONMENT }}
     defaults:
       run:
-        working-directory: ./
+        working-directory: ./  
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -44,8 +44,20 @@ jobs:
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           echo "Image Version: $VERSION"
 
-      - name: Build and Push Docker Image
-        if: env.BRANCH == 'dev'
+      - name: Build and Push Docker Image for Main
+        if: ${{ env.BRANCH == 'main' }}
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
+        run: |
+          IMAGE_TAG="${VERSION}"
+          echo "Final Image Tag: $IMAGE_TAG"
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+      - name: Build and Push Docker Image for Dev
+        if: ${{ env.BRANCH == 'dev' }}
+        id: build-image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
@@ -55,17 +67,7 @@ jobs:
           echo "Final Image Tag: $IMAGE_TAG"
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-
-      - name: Build and Push Docker Image for Main
-        if: env.BRANCH == 'main'
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
-        run: |
-          IMAGE_TAG="${VERSION}"
-          echo "Final Image Tag: $IMAGE_TAG"
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
 
       - name: Push Git Tag
         env:
@@ -76,6 +78,112 @@ jobs:
           git config user.email "actions@github.com"
           git tag $IMAGE_TAG
           git push origin $IMAGE_TAG
+
+      - name: Download Task Definition
+        if: ${{ env.BRANCH == 'dev' }}
+        run: |
+          aws ecs describe-task-definition --task-definition test-mf-dev-mf-nginx-task-def --query taskDefinition > task-definition.json
+          
+      - name: Fill in new Image ID in Task Definition
+        if: ${{ env.BRANCH == 'dev' }}
+        id: task-def
+        uses: aws-actions/amazon-ecs-render-task-definition@v1
+        with:
+          task-definition: task-definition.json
+          container-name: test-mf-dev-container
+          image: ${{ steps.build-image.outputs.image }}
+
+      - name: Deploy Amazon ECS Task Definition
+        if: ${{ env.BRANCH == 'dev' }}
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
+        with:
+          task-definition: ${{ steps.task-def.outputs.task-definition }}
+          service: test-mf-dev-mutual-funds
+          cluster: test-dev-cluster
+          wait-for-service-stability: true
+
+
+
+
+
+# name: Build docker image and upload to ECR
+
+# on:
+#   workflow_call:
+#     inputs:
+#       ENVIRONMENT:
+#         type: string
+#         required: true
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     environment: ${{ inputs.ENVIRONMENT }}
+#     defaults:
+#       run:
+#         working-directory: ./
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
+
+#       - name: Set Branch
+#         id: set-branch
+#         run: echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
+
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v2
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
+#           aws-region: ${{ vars.AWS_REGION }}
+
+#       - name: Login to Amazon ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v1
+
+#       - name: Extract Version
+#         id: version
+#         run: |
+#           VERSION=$(sed -nE 's/^\s*"version": "(.*?)",?$/\1/p' release.json)
+#           if [[ -z "$VERSION" ]]; then
+#             echo "Error: Could not extract version from release.json"
+#             exit 1
+#           fi
+#           echo "VERSION=$VERSION" >> $GITHUB_ENV
+#           echo "Image Version: $VERSION"
+
+#       - name: Build and Push Docker Image
+#         if: env.BRANCH == 'dev'
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
+#         run: |
+#           TAG_SUFFIX=".dev"
+#           IMAGE_TAG="${VERSION}${TAG_SUFFIX}"
+#           echo "Final Image Tag: $IMAGE_TAG"
+#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+#       - name: Build and Push Docker Image for Main
+#         if: env.BRANCH == 'main'
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
+#         run: |
+#           IMAGE_TAG="${VERSION}"
+#           echo "Final Image Tag: $IMAGE_TAG"
+#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+#       - name: Push Git Tag
+#         env:
+#           TAG_SUFFIX: ${{ env.BRANCH == 'dev' && '.dev' || '' }}
+#         run: |
+#           IMAGE_TAG="${VERSION}${TAG_SUFFIX}"
+#           git config user.name "GitHub Actions"
+#           git config user.email "actions@github.com"
+#           git tag $IMAGE_TAG
+#           git push origin $IMAGE_TAG
 
 
 
