ty

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,4 +1,4 @@
-name: Build docker image and upload to ECR
+name: Build Docker Image and Upload to ECR
 
 on:
   workflow_call:
@@ -56,7 +56,7 @@ jobs:
           echo "Final Image Tag: $IMAGE_TAG"
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
 
       - name: Build and Push Docker Image for Main
         if: ${{ env.BRANCH == 'main' }}
@@ -81,18 +81,35 @@ jobs:
           git tag $IMAGE_TAG
           git push origin $IMAGE_TAG
 
+    outputs:
+      image: ${{ env.image }}
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build  # This ensures the deploy job runs after the build job succeeds.
+    environment: ${{ inputs.ENVIRONMENT }}
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
+          aws-region: ${{ vars.AWS_REGION }}
 
       - name: Download task definition 
         run: |
           aws ecs describe-task-definition --task-definition test-mf-dev-mf-nginx-task-def --query taskDefinition > task-definition.json
-          
+
       - name: Fill in new image ID in task definition
         id: task-def
         uses: aws-actions/amazon-ecs-render-task-definition@v1
         with:
          task-definition: task-definition.json 
          container-name: test-mf-dev-container
-         image: ${{ steps.build-image.outputs.image }}
+         image: ${{ needs.build.outputs.image }}
 
       - name: Deploy Amazon ECS task definition
         uses: aws-actions/amazon-ecs-deploy-task-definition@v2
@@ -101,6 +118,123 @@ jobs:
           service: test-mf-dev-mutual-funds
           cluster: test-dev-cluster
           wait-for-service-stability: true
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# name: Build docker image and upload to ECR
+
+# on:
+#   workflow_call:
+#     inputs:
+#       ENVIRONMENT:
+#         type: string
+#         required: true
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     environment: ${{ inputs.ENVIRONMENT }}
+#     defaults:
+#       run:
+#         working-directory: ./  
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
+
+#       - name: Set Branch
+#         id: set-branch
+#         run: echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
+
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v2
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
+#           aws-region: ${{ vars.AWS_REGION }}
+
+#       - name: Login to Amazon ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v1
+
+#       - name: Extract Version
+#         id: version
+#         run: |
+#           VERSION=$(sed -nE 's/^\s*"version": "(.*?)",?$/\1/p' release.json)
+#           if [[ -z "$VERSION" ]]; then
+#             echo "Error: Could not extract version from release.json"
+#             exit 1
+#           fi
+#           echo "VERSION=$VERSION" >> $GITHUB_ENV
+#           echo "Image Version: $VERSION"
+
+#       - name: Build and Push Docker Image for Dev
+#         if: ${{ env.BRANCH == 'dev' }}
+#         id: build-image
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
+#         run: |
+#           TAG_SUFFIX=".dev"
+#           IMAGE_TAG="${VERSION}${TAG_SUFFIX}"
+#           echo "Final Image Tag: $IMAGE_TAG"
+#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+#           echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+
+#       - name: Build and Push Docker Image for Main
+#         if: ${{ env.BRANCH == 'main' }}
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
+#         run: |
+#           IMAGE_TAG="${VERSION}"
+#           echo "Final Image Tag: $IMAGE_TAG"
+#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#           docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
+#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
+
+#       - name: Push Git Tag
+#         env:
+#           TAG_SUFFIX: ${{ github.ref_name == 'dev' && '.dev' || '' }}
+#         run: |
+#           IMAGE_TAG="${VERSION}${TAG_SUFFIX}"
+#           git config user.name "GitHub Actions"
+#           git config user.email "actions@github.com"
+#           git tag $IMAGE_TAG
+#           git push origin $IMAGE_TAG
+
+
+#       - name: Download task definition 
+#         run: |
+#           aws ecs describe-task-definition --task-definition test-mf-dev-mf-nginx-task-def --query taskDefinition > task-definition.json
+          
+#       - name: Fill in new image ID in task definition
+#         id: task-def
+#         uses: aws-actions/amazon-ecs-render-task-definition@v1
+#         with:
+#          task-definition: task-definition.json 
+#          container-name: test-mf-dev-container
+#          image: ${{ steps.build-image.outputs.image }}
+
+#       - name: Deploy Amazon ECS task definition
+#         uses: aws-actions/amazon-ecs-deploy-task-definition@v2
+#         with:
+#           task-definition: ${{ steps.task-def.outputs.task-definition }}
+#           service: test-mf-dev-mutual-funds
+#           cluster: test-dev-cluster
+#           wait-for-service-stability: true
 
 
 
