7

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -6,10 +6,6 @@ on:
       - dev
       - main
 
-env:
-  AWS_REGION: ${{ env.AWS_REGION }}
-  ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
-
 jobs:
   build-and-push-image:
     runs-on: ubuntu-latest
@@ -25,7 +21,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+          aws-region: ${{ vars.AWS_REGION }} # Accessing repository variables
 
       - name: Login to Amazon ECR
         id: login-ecr
@@ -42,12 +38,12 @@ jobs:
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           echo "Image Version: $VERSION"
 
-
       - name: Build and Push Docker Image
         id: build-image
         if: github.ref_name == matrix.branch
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }} # Accessing repository variables
         run: |
           TAG_SUFFIX=""
           if [[ "${{ matrix.branch }}" == "dev" ]]; then
@@ -70,6 +66,96 @@ jobs:
           git config user.email "actions@github.com"
           git tag $IMAGE_TAG
           git push origin $IMAGE_TAG
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# name: AWS ECS Deployment
+
+# on:
+#   push:
+#     branches:
+#       - dev
+#       - main
+
+# env:
+#   AWS_REGION: ${{ env.AWS_REGION }}
+#   ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
+
+# jobs:
+#   build-and-push-image:
+#     runs-on: ubuntu-latest
+#     strategy:
+#       matrix:
+#         branch: [dev, main]
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
+
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v2
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
+#           aws-region: ${{ env.AWS_REGION }}
+
+#       - name: Login to Amazon ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v1
+
+#       - name: Extract Version
+#         id: version
+#         run: |
+#           VERSION=$(sed -nE 's/^\s*"version": "(.*?)",?$/\1/p' release.json)
+#           if [[ -z "$VERSION" ]]; then
+#             echo "Error: Could not extract version from release.json"
+#             exit 1
+#           fi
+#           echo "VERSION=$VERSION" >> $GITHUB_ENV
+#           echo "Image Version: $VERSION"
+
+
+#       - name: Build and Push Docker Image
+#         id: build-image
+#         if: github.ref_name == matrix.branch
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#         run: |
+#           TAG_SUFFIX=""
+#           if [[ "${{ matrix.branch }}" == "dev" ]]; then
+#             TAG_SUFFIX=".dev"
+#           fi
+#           IMAGE_TAG="${VERSION}${TAG_SUFFIX}"
+#           echo "Final Image Tag: $IMAGE_TAG"
+#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+#       - name: Push Git Tag
+#         if: github.ref_name == matrix.branch
+#         run: |
+#           TAG_SUFFIX=""
+#           if [[ "${{ matrix.branch }}" == "dev" ]]; then
+#             TAG_SUFFIX=".dev"
+#           fi
+#           IMAGE_TAG="${VERSION}${TAG_SUFFIX}"
+#           git config user.name "GitHub Actions"
+#           git config user.email "actions@github.com"
+#           git tag $IMAGE_TAG
+#           git push origin $IMAGE_TAG
 
 
 
